### ISSUE TITLE
Bug: number divisible by 0

### ISSUE THREAD

**Issue by DivyanshiNarang** [mohitahlawat2001/calculator-app#11]
any number / 0 = Error 
but here it is showing Infinity which is not correct. 

I can improve it.

**Comment by rajatuiwebdev** [comment]
I've also spotted this bug. I can fix it.

**Comment by DivyanshiNarang** [comment]
Ihey @rajatuiwebdev, am working on this issue.

**Comment by rajatuiwebdev** [comment]
Hey @DivyanshiNarang I've fixed that already. Just waiting for it to be assigned so I can make a pull request.
