### ISSUE TITLE
Weird display in case of long expressions

### ISSUE THREAD

**Issue by srbmaury** [mohitahlawat2001/calculator-app#27]
![image](https://github.com/mohitahlawat2001/calculator-app/assets/85755081/3843e856-a93e-4862-b2b2-7911babb9937)

**Comment by shivanshsin0203** [comment]
I too want to work on this issue

**Comment by srbmaury** [comment]
@mohitahlawat2001 you may assign this to @shivanshsin0203

**Comment by love-sonkar** [comment]
this issue is not fixed after merging the PR can i work on this

**Comment by love-sonkar** [comment]
@mohitahlawat2001 should i make another issue for this or just create a PR.
