### ISSUE TITLE
NaN on toggling negative number

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [mohitahlawat2001/calculator-app#3]
**Problem:** When performing arithmetic operations involving sign toggling, such as subtracting a negative number or multiplying/dividing by a negative number, unexpected results or errors may occur.

**Example:**
`5 - -7`: Attempting to subtract a negative number from another number can lead to issues. In this case, it might be interpreted as a sign change, causing unexpected behavior.
`3 × -4`: Multiplying a number by a negative value can also result in unexpected outcomes, especially when negative values are not handled correctly.

**Expected Behavior:** Mathematical operations should yield consistent and predictable results, regardless of the sign of the numbers involved.

**Current Behavior:** Some operations may produce NaN (Not-a-Number) errors or unexpected results, making it challenging to perform calculations accurately.

I have fixed this issue, I just need to do a pull request on this repository. You can assign this to me, Thanks

![image](https://github.com/mohitahlawat2001/calculator-app/assets/62497214/894227d9-72da-4e2e-a3b5-63abddcc7da3)

**Comment by Dimas-Saputra-Me** [comment]
@mohitahlawat2001 I have made a pull-request (#19) regarding to fix this issue. Let me know if there is any feedback or I need to do something on it. Thanks

**Comment by mohitahlawat2001** [comment]
thank you
