### ISSUE TITLE
Adding a heading.

### ISSUE THREAD

**Issue by Vatsalmadhur** [mohitahlawat2001/calculator-app#5]
I want to add a "Calculator" heading.

**Comment by Vatsalmadhur** [comment]
i request you to please assign me this issue.

**Comment by MGCodes123** [comment]
If you are in tkinter...
Just after you create a window type the_name_of_your_window.title("Title")

**Comment by Vatsalmadhur** [comment]
Please check pr #31

**Comment by Vatsalmadhur** [comment]
Why is this closed???

**Comment by mansi1309** [comment]
Hello @mohitahlawat2001 can you please assign it to me .
