### ISSUE TITLE
Adding one more operation button to calculate the LCM of 2 numbers

### ISSUE THREAD

**Issue by ctln23** [mohitahlawat2001/calculator-app#52]
It will take 2 numbers as input from the user and calculates the LCM of the numbers and prints it

**Comment by ctln23** [comment]
@mohitahlawat2001 I would like to work on this. Kindly assign it to me.

**Comment by ctln23** [comment]
@mohitahlawat2001, Thank you for assigning this issue to me. I kindly request you to add the required hacktoberfest labels as well if possible

**Comment by HARSHITHASALADI1** [comment]
Could you please assign me this task?
